### ISSUE TITLE
write_ods does not preserve NA values

### ISSUE THREAD

**Issue by RJDan** [ropensci/readODS#79] opened 2022-02-20 16:48 UTC
Actions:
Exporting an ods file from a matrix.
``` 
tmp.mat %>% as_tibble %>% mutate(rownames = tmp.names) %>% write_ods(.,path=outputname,col_names=T,row_names=T,update=T,append=T,sheet='pvalueTables2')
## or


tmp.mat %>% as_tibble %>% mutate(rownames = tmp.names) %>% as.data.frame %>% write_ods(.,path=outputname,col_names=T,row_names=T,update=T,append=T,sheet='pvalueTables2')
```

Actual behaviour:
When exporting a tibble or data.frame object with write_ods, the output document has all the NA values replaced with 0.

Expected behaviour:
write_ods does preserve NA values; a distinction is made between NA and 0.

**Comment by chainsawriot** [comment] 2022-02-21 10:44
@RJDan Thanks for reporting this. Could you please share with me the content of your `tmp.mat`? I can't reproduce your error with a NA-ridden matrix I created.

``` r
require(readODS)
#> Loading required package: readODS
require(tibble)
#> Loading required package: tibble

test_df <- tibble::tibble(x = c(NA, 1, 2, 3, 4), y = c(0, 0, NA, 0, 0))
write_ods(test_df, "write_na.ods")
read_ods("write_na.ods")
#>    x  y
#> 1 NA  0
#> 2  1  0
#> 3  2 NA
#> 4  3  0
#> 5  4  0

matrix(c(NA, 1, 2, 3, 4, 0, 0, NA, 0, 0), nrow = 2, byrow = TRUE) %>% as_tibble() %>% write_ods("write_na2.ods")
#> Warning: The `x` argument of `as_tibble.matrix()` must have unique column names if `.name_repair` is omitted as of tibble 2.0.0.
#> Using compatibility `.name_repair`.
#> This warning is displayed once every 8 hours.
#> Call `lifecycle::last_lifecycle_warnings()` to see where this warning was generated.
read_ods("write_na2.ods")
#>   V1 V2 V3 V4 V5
#> 1 NA  1  2  3  4
#> 2  0  0 NA  0  0

sessionInfo()
#> R version 4.1.2 (2021-11-01)
#> Platform: x86_64-pc-linux-gnu (64-bit)
#> Running under: Ubuntu 20.04.3 LTS
#> 
#> Matrix products: default
#> BLAS:   /usr/lib/x86_64-linux-gnu/atlas/libblas.so.3.10.3
#> LAPACK: /usr/lib/x86_64-linux-gnu/atlas/liblapack.so.3.10.3
#> 
#> locale:
#>  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
#>  [3] LC_TIME=de_DE.UTF-8        LC_COLLATE=en_US.UTF-8    
#>  [5] LC_MONETARY=de_DE.UTF-8    LC_MESSAGES=en_US.UTF-8   
#>  [7] LC_PAPER=de_DE.UTF-8       LC_NAME=C                 
#>  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
#> [11] LC_MEASUREMENT=de_DE.UTF-8 LC_IDENTIFICATION=C       
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] tibble_3.1.6  readODS_1.7.2
#> 
#> loaded via a namespace (and not attached):
#>  [1] pillar_1.6.5      compiler_4.1.2    highr_0.9         R.methodsS3_1.8.1
#>  [5] R.utils_2.11.0    tools_4.1.2       digest_0.6.29     evaluate_0.14    
#>  [9] lifecycle_1.0.1   R.cache_0.15.0    pkgconfig_2.0.3   rlang_1.0.0      
#> [13] reprex_2.0.1      cli_3.1.1         yaml_2.2.2        xfun_0.29        
#> [17] fastmap_1.1.0     withr_2.4.3       styler_1.6.2      stringr_1.4.0    
#> [21] knitr_1.37        xml2_1.3.3        fs_1.5.2          vctrs_0.3.8      
#> [25] hms_1.1.1         glue_1.6.1        R6_2.5.1          fansi_1.0.2      
#> [29] rmarkdown_2.11    purrr_0.3.4       readr_2.1.1       tzdb_0.2.0       
#> [33] magrittr_2.0.2    backports_1.4.1   ellipsis_0.3.2    htmltools_0.5.2  
#> [37] utf8_1.2.2        stringi_1.7.6     crayon_1.4.2      R.oo_1.24.0
```

<sup>Created on 2022-02-21 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by koheiw** [comment] 2023-03-10 08:17
I can confirm that NAs are preserved  in the round trip.
```
> require(readODS)
> test_df <- data.frame(x = c(NA, 1, 2, 3, 4), y = c(0, 0, NA, 0, 0))
> write_ods(test_df, "write_na.ods")
> read_ods("write_na.ods")
   x  y
1 NA  0
2  1  0
3  2 NA
4  3  0
5  4  0
```
But, if I open the ODS file in Calc, NAs are all zero.

<img width="182" alt="Screenshot 2023-03-10 171422" src="https://user-images.githubusercontent.com/6572963/224261025-8520def8-884c-4827-8a21-a1b2fe669dfb.png">

**Comment by chainsawriot** [comment] 2023-03-12 09:45
@koheiw Thanks for the reporting. Now I can understand what the problem is. This is the generated XML of the row 4.

```xml
<table:table-row>
<table:table-cell office:value-type="float" office:value="2" table:style-name="ce1">
<text:p>2</text:p></table:table-cell>
<table:table-cell office:value-type="float" office:value="NA" table:style-name="ce1">
<text:p>NA</text:p></table:table-cell></table:table-row>
```

The gist of the problem is that LibreOffice (Google Sheets as well) doesn't know how to render a float value of NA and therefore displays it as the default value: 0.

One way to "fix" this, is to treat `NA` as string.

**Comment by koheiw** [comment] 2023-03-12 10:54
You could allow users to decide whether code NAs as 0 or "NA" through an argument, but I would choose the latter always because I export data to ODS for eyeball checks.

**Comment by chainsawriot** [comment] 2023-03-12 16:38
@koheiw @RJDan I think this is now fixed. The new argument `na_as_string` is added. By default, it is `getOption("write_ods_na", default = FALSE)` for backward compatibility.

If you want to make it the default, put `option("write_ods_na" = TRUE)` either in your script or your `.Rprofile`.

This will be TRUE by default in the next major release (v2).

**Comment by koheiw** [comment] 2023-03-12 22:24
Thanks for fixing it so quickly. The option is very useful for me. 

I noticed that `writexl::write_xlsx()` leaves NA cells blank. This is an another approach.

**Comment by chainsawriot** [comment] 2023-07-26 13:38
As we have some time due to the CRAN summer vacation, I think we need to talk about what's the best way to handle this for Version 2.0 (the last opportunity for us to introduce breaking changes before v3.0). I now feel that it's better to write NA as blank (the default of `writexl`) rather than as string.

``` r
iris_na <- tibble::as_tibble(iris)
iris_na[1,1] <- NA
iris_na$Species <- as.character(iris_na$Species)
all.equal(iris_na, readxl::read_xlsx(writexl::write_xlsx(iris_na)))
#> [1] TRUE

all.equal(iris_na, readODS::read_ods(readODS::write_ods(iris_na, tempfile(fileext = ".ods"))))
#> [1] "Component \"Sepal.Length\": Modes: numeric, character"              
#> [2] "Component \"Sepal.Length\": target is numeric, current is character"
```

<sup>Created on 2023-07-26 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Closed** 2023-07-26 21:17 UTC
Labels: bug, v2.0
